#include "error.h"

const char* ASTResultTypeMap[] = {
    [AST_RES_OK] = "AST_RES_OK",
    [AST_RES_ERR_ID_ALREADY_DEFINED] = "AST_RES_ERR_ID_ALREADY_DEFINED",
    [AST_RES_ERR_ID_NOT_DEFINED] = "AST_RES_ERR_ID_NOT_DEFINED",
    [AST_RES_ERR_ID_NOT_INIT] = "AST_RES_ERR_ID_NOT_INIT",
    [AST_RES_ERR_DIFFERENT_TYPES] = "AST_RES_ERR_DIFFERENT_TYPES",
    [AST_RES_ERR_INVALID_CHILD_TYPE] = "AST_RES_ERR_INVALID_CHILD_TYPE",
    [AST_RES_ERR_INVALID_LEFT_TYPE] = "AST_RES_ERR_INVALID_LEFT_TYPE",
    [AST_RES_ERR_INVALID_RIGHT_TYPE] = "AST_RES_ERR_INVALID_RIGHT_TYPE",
    [AST_RES_ERR_NON_TRANSITIVE_CHAINING] = "AST_RES_ERR_NON_TRANSITIVE_CHAINING",
//    [AST_RES_TYPE_COUNT] = "AST_RES_TYPE_COUNT"
};